---
title: 'Methods for exploring and modeling intensive longitudinal data: implementations in R'
lesson: 'Lesson 1'
author: "Dario Baretta"
date: "01/09/2022"
output:
  pdf_document: default
  html_document: default
---

# Lesson 2

## Preliminary steps

### Set working directory

```{r setup, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
```

### Load packages

```{r}
# if the packages are not installed, first you need to install them using the install.packages() function
library(tidyverse) # to do most of the data wrangling stuff
library(lubridate) # to make your life with dates easier
library(zoo) # to calculate rolling functions
library(gridExtra) # to merge different plot in a single page

```

## purrr

### map() to import multiple files

If you have to import the TS one by one, the code would look like the next chunk. As you can see it might be quite inconvenient if you have to repeat it multiple times, say 10, 100 times. Did you use this approach for the homework?

```{r}
# an inconvenient way
P344 <- read_csv("P344.csv") %>% 
  mutate(id = 'P344') %>% 
  select(id, date, steps) %>% 
  mutate(prog_day = seq_along(date))
P388 <- read_csv("P388.csv") %>% 
  mutate(id = 'P388') %>% 
  select(id, date, steps)%>% 
  mutate(prog_day = seq_along(date))
P246 <- read_csv("P246.csv") %>% 
  mutate(id = 'P246') %>% 
  select(id, date, steps)%>% 
  mutate(prog_day = seq_along(date))



```

```{r}
Personen <- merge(merge(
    P246,
    P344, all = TRUE),
    P388, all = TRUE)

```

------------------------------------------------------------------------
```{r}
P344 %>% 
  ggplot(aes(x = date, y = steps)) +
  geom_line() +
  theme_minimal() # you can choose between different themes to change the aestethics of the background

```

```{r}
Personen %>% 
  mutate(rolling_steps = zoo::rollmean(steps, 7, align = 'right', fill = NA, na.rm = TRUE)) %>%
  ggplot(aes(x = prog_day, y = steps, colour = id)) +
  geom_line(aes(y = rolling_steps)) +
  xlab("Study Day") +
  ylab("Steps(7 Day rolling average)") +
  theme_minimal()


```

```{r}
Personen %>% 
  mutate(rolling_steps = zoo::rollmean(steps, 7, align = 'right', fill = NA, na.rm = TRUE)) %>%
  ggplot(aes(x = prog_day, y = steps, colour = id)) +
  geom_line(aes(y = rolling_steps)) +
  xlab("Study Day") +
  ylab("Steps(7 Day rolling average)") +
  theme_minimal()+ 
    facet_grid(. ~ id)
```